import Foundation

struct PassObject: Codable, Identifiable, Equatable, Hashable {
    var id: UUID
    var passName: String
    var passType: PassType
    var passIcon: Data
    var identificationString: String
    var barcodeString: String
    var barcodeType: BarcodeType
    var barcodeBorder: Double
    var stripImage: Data // PNG data for all passes that use the strip image (may be a barcode, picture, etc)
    var backgroundImage: Data // PNG data for all passes that use the background image
    var logoImage: Data // PNG data for all passes that use the logo image
    var qrCodeString: String
    var qrCodeCorrectionLevel: QrCodeCorrectionLevel
    var noteString: String
    var name: String
    var title: String
    var businessName: String
    var phoneNumber: String
    var email: String
    var pictureData: Data
    var foregroundColor: UInt
    var backgroundColor: UInt
    var labelColor: UInt
    var description: String
    var isHeaderFieldOneOn: Bool
    var headerFieldOneLabel: String
    var headerFieldOneText: String
    var isHeaderFieldTwoOn: Bool
    var headerFieldTwoLabel: String
    var headerFieldTwoText: String
    /* Technically, PassKit supports a third header field, but the space available is so tight that a third one is effectively useless. Maybe this will change later */
    var isPrimaryFieldOn: Bool
    var primaryFieldLabel: String
    var primaryFieldText: String
    var isSecondaryFieldOneOn: Bool
    var secondaryFieldOneLabel: String
    var secondaryFieldOneText: String
    var isSecondaryFieldTwoOn: Bool
    var secondaryFieldTwoLabel: String
    var secondaryFieldTwoText: String
}

extension PassObject {
    init() {
        id = UUID()
        passName = ""
        passType = PassType.barcodePass
        passIcon = (try? Data(contentsOf: Bundle.main.url(forResource: "DefaultPassIcon", withExtension: "png") ?? URL(fileURLWithPath: ""))) ?? Data()
        identificationString = ""
        barcodeString = ""
        barcodeType = BarcodeType.code128
        barcodeBorder = 0
        stripImage = Data()
        backgroundImage = Data()
        logoImage = Data()
        qrCodeString = ""
        qrCodeCorrectionLevel = QrCodeCorrectionLevel.medium
        noteString = ""
        name = ""
        title = ""
        businessName = ""
        phoneNumber = ""
        email = ""
        pictureData = Data()
        foregroundColor = 0x000000
        backgroundColor = 0xFFFFFF
        labelColor = 0x000000
        description = "A Wallet Pass generated by PassKeepr"
        isHeaderFieldOneOn = false
        isHeaderFieldTwoOn = false
        headerFieldOneLabel = ""
        headerFieldOneText = ""
        headerFieldTwoLabel = ""
        headerFieldTwoText = ""
        isPrimaryFieldOn = false
        primaryFieldLabel = ""
        primaryFieldText = ""
        isSecondaryFieldOneOn = false
        secondaryFieldOneLabel = ""
        secondaryFieldOneText = ""
        isSecondaryFieldTwoOn = false
        secondaryFieldTwoLabel = ""
        secondaryFieldTwoText = ""
    }

    func duplicate() -> PassObject {
        var newObject = PassObject()
        newObject.passName = passName
        newObject.passType = passType
        newObject.passIcon = passIcon
        newObject.identificationString = identificationString
        newObject.barcodeString = barcodeString
        newObject.barcodeType = barcodeType
        newObject.barcodeBorder = barcodeBorder
        newObject.stripImage = stripImage
        newObject.backgroundImage = backgroundImage
        newObject.logoImage = logoImage
        newObject.qrCodeString = qrCodeString
        newObject.qrCodeCorrectionLevel = qrCodeCorrectionLevel
        newObject.noteString = noteString
        newObject.name = name
        newObject.title = title
        newObject.businessName = businessName
        newObject.phoneNumber = phoneNumber
        newObject.email = email
        newObject.pictureData = pictureData
        newObject.foregroundColor = foregroundColor
        newObject.backgroundColor = backgroundColor
        newObject.labelColor = labelColor
        newObject.description = description
        newObject.isHeaderFieldOneOn = isHeaderFieldOneOn
        newObject.headerFieldOneLabel = headerFieldOneLabel
        newObject.headerFieldOneText = headerFieldOneText
        newObject.isHeaderFieldTwoOn = isHeaderFieldTwoOn
        newObject.headerFieldTwoLabel = headerFieldTwoLabel
        newObject.headerFieldTwoText = headerFieldTwoText
        newObject.isPrimaryFieldOn = isPrimaryFieldOn
        newObject.primaryFieldLabel = primaryFieldLabel
        newObject.primaryFieldText = primaryFieldText
        newObject.isSecondaryFieldOneOn = isSecondaryFieldOneOn
        newObject.secondaryFieldOneLabel = secondaryFieldOneLabel
        newObject.secondaryFieldOneText = secondaryFieldOneText
        newObject.isSecondaryFieldTwoOn = isSecondaryFieldTwoOn
        newObject.secondaryFieldTwoLabel = secondaryFieldTwoLabel
        newObject.secondaryFieldTwoText = secondaryFieldTwoText
        return newObject
    }
}

enum PassType: Int, Codable, Identifiable, CaseIterable {
    case identificationPass, barcodePass, qrCodePass, notePass, businessCardPass, picturePass
    var id: Self { self }
}

enum QrCodeCorrectionLevel: Codable, CustomStringConvertible, CaseIterable {
    case low
    case medium
    case quartile
    case high

    var description: String {
        switch self {
        case .low: return "L"
        case .medium: return "M"
        case .quartile: return "Q"
        case .high: return "H"
        }
    }
}

enum BarcodeType: Codable, CustomStringConvertible, CaseIterable {
    case code128 // natively supported by PassKit
    case code93
    case code39
    case upce

    var description: String {
        switch self {
        case .code128: return "Code 128"
        case .code93: return "Code 93"
        case .code39: return "Code 39"
        case .upce: return "UPC-E"
        }
    }
}
