import Foundation
import SwiftUI

struct PassObject: Codable, Identifiable, Equatable, Hashable, Transferable {
    var id: UUID
    var passIcon: Data
    var barcodeString: String
    var barcodeType: BarcodeType
    var barcodeBorder: Double
    var stripImage: Data // PNG data for all passes that use the strip image (may be a barcode, picture, etc)
    var backgroundImage: Data // PNG data for all passes that use the background image
    var logoImage: Data // PNG data for all passes that use the logo image
    var logoImageType: LogoImageType
    var qrCodeCorrectionLevel: QrCodeCorrectionLevel
    var qrCodeEncoding: QrCodeEncoding
    var altText: String
    var foregroundColor: UInt
    var backgroundColor: UInt
    var labelColor: UInt
    var description: String
    var headerFieldOneLabel: String
    var headerFieldOneText: String
    var isHeaderFieldTwoOn: Bool
    var headerFieldTwoLabel: String
    var headerFieldTwoText: String
    /* Technically, PassKit supports a third header field, but the space available is so tight that a third one is effectively useless. Maybe this will change later */
    var primaryFieldLabel: String
    var primaryFieldText: String
    var secondaryFieldOneLabel: String
    var secondaryFieldOneText: String
    var isSecondaryFieldTwoOn: Bool
    var secondaryFieldTwoLabel: String
    var secondaryFieldTwoText: String
    var isSecondaryFieldThreeOn: Bool
    var secondaryFieldThreeLabel: String
    var secondaryFieldThreeText: String
    var isCustomStripImageOn: Bool
    var logoSymbolName: String
    var logoSymbolColor: UInt

    static var transferRepresentation: some TransferRepresentation {
        CodableRepresentation(contentType: .data)
    }
}

extension PassObject {
    init() {
        id = UUID()
        passIcon = (try? Data(contentsOf: Bundle.main.url(forResource: "DefaultPassIcon", withExtension: "png") ?? URL(fileURLWithPath: ""))) ?? Data()
        barcodeString = ""
        barcodeType = BarcodeType.none
        barcodeBorder = 0
        stripImage = Data()
        backgroundImage = Data()
        logoImage = Data()
        logoImageType = LogoImageType.none
        qrCodeCorrectionLevel = QrCodeCorrectionLevel.medium
        qrCodeEncoding = QrCodeEncoding.ascii
        altText = ""
        foregroundColor = 0x000000
        backgroundColor = 0xFFFFFF
        labelColor = 0x000000
        description = "Pass generated by PassKeepr"
        isHeaderFieldTwoOn = false
        headerFieldOneLabel = ""
        headerFieldOneText = ""
        headerFieldTwoLabel = ""
        headerFieldTwoText = ""
        primaryFieldLabel = ""
        primaryFieldText = ""
        secondaryFieldOneLabel = ""
        secondaryFieldOneText = ""
        isSecondaryFieldTwoOn = false
        secondaryFieldTwoLabel = ""
        secondaryFieldTwoText = ""
        isSecondaryFieldThreeOn = false
        secondaryFieldThreeLabel = ""
        secondaryFieldThreeText = ""
        isCustomStripImageOn = false
        logoSymbolName = ""
        logoSymbolColor = 0x000000
    }

    func duplicate() -> PassObject {
        var newObject = PassObject()
        newObject.passIcon = passIcon
        newObject.barcodeString = barcodeString
        newObject.barcodeType = barcodeType
        newObject.barcodeBorder = barcodeBorder
        newObject.stripImage = stripImage
        newObject.backgroundImage = backgroundImage
        newObject.logoImage = logoImage
        newObject.logoImageType = logoImageType
        newObject.qrCodeCorrectionLevel = qrCodeCorrectionLevel
        newObject.qrCodeEncoding = qrCodeEncoding
        newObject.altText = altText
        newObject.foregroundColor = foregroundColor
        newObject.backgroundColor = backgroundColor
        newObject.labelColor = labelColor
        newObject.description = description
        newObject.headerFieldOneLabel = headerFieldOneLabel
        newObject.headerFieldOneText = headerFieldOneText
        newObject.isHeaderFieldTwoOn = isHeaderFieldTwoOn
        newObject.headerFieldTwoLabel = headerFieldTwoLabel
        newObject.headerFieldTwoText = headerFieldTwoText
        newObject.primaryFieldLabel = primaryFieldLabel
        newObject.primaryFieldText = primaryFieldText
        newObject.secondaryFieldOneLabel = secondaryFieldOneLabel
        newObject.secondaryFieldOneText = secondaryFieldOneText
        newObject.isSecondaryFieldTwoOn = isSecondaryFieldTwoOn
        newObject.secondaryFieldTwoLabel = secondaryFieldTwoLabel
        newObject.secondaryFieldTwoText = secondaryFieldTwoText
        newObject.isSecondaryFieldThreeOn = isSecondaryFieldThreeOn
        newObject.secondaryFieldThreeLabel = secondaryFieldThreeLabel
        newObject.secondaryFieldThreeText = secondaryFieldThreeText
        newObject.isCustomStripImageOn = isCustomStripImageOn
        newObject.logoSymbolName = logoSymbolName
        newObject.logoSymbolColor = logoSymbolColor
        return newObject
    }
}

enum QrCodeCorrectionLevel: Codable, CustomStringConvertible, CaseIterable {
    case low
    case medium
    case quartile
    case high

    var description: String {
        switch self {
        case .low: return "L"
        case .medium: return "M"
        case .quartile: return "Q"
        case .high: return "H"
        }
    }
}

enum QrCodeEncoding: Codable, CustomStringConvertible, CaseIterable {
    case ascii
    case utf8
    case unicode

    func toStringEncoding() -> String.Encoding {
        switch self {
        case .ascii: return .ascii
        case .utf8: return .utf8
        case .unicode: return .unicode
        }
    }

    var description: String {
        switch self {
        case .ascii: return "ASCII"
        case .utf8: return "UTF-8"
        case .unicode: return "Unicode"
        }
    }
}

enum BarcodeType: Codable, CustomStringConvertible, Identifiable, CaseIterable {
    case none
    case code128 // natively supported by PassKit
    case code93
    case code39
    case upce
    case upca
    case ean13
    case pdf417 // natively supported by PassKit
    case qr

    var description: String {
        switch self {
        case .none: return "None"
        case .code128: return "Code 128"
        case .code93: return "Code 93"
        case .code39: return "Code 39"
        case .upce: return "UPC-E"
        case .upca: return "UPC-A"
        case .ean13: return "EAN-13"
        case .pdf417: return "PDF417"
        case .qr: return "QR Code"
        }
    }

    var id: Self { self }
}

enum LogoImageType: Codable, CustomStringConvertible, CaseIterable {
    case photo
    case emoji
    case symbol
    case none

    var description: String {
        switch self {
        case .photo: return "Photo"
        case .emoji: return "Emoji"
        case .symbol: return "Symbol"
        case .none: return "None"
        }
    }
}

enum BarcodeCategory: CaseIterable, CustomStringConvertible {
    case none
    case oneDimensional
    case twoDimensional

    var description: String {
        switch self {
        case .none: return "None"
        case .oneDimensional: return "1D Barcode"
        case .twoDimensional: return "2D Barcode"
        }
    }
}
